apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 417512664386.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 417512664386.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 63151a90
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
